version: "3"
services:
  scraper:
    build: .
    environment: 
      - REDIS_HOST=redis
    image: "scraper"
    
  redis:
    image: "redis"
    
  mongo:
    image: "mongo"
    ports:
      - '27017:27017'
